anchor-params:
  data-directory: &data-directory C:/work/tmp
  mail-address: &mail-address XXXXXXXX@test.com

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 50MB
      location: *data-directory
      resolve-lazily: false
  web:
    resources:
      cache:
        period: 0
  mvc:
    throw-exception-if-no-handler-found: true
  #messages: # *Configure the message source with the MessageSourceConfig class to implement custom annotations using Bean Validation.
  #  basename: messages
  #  cache-duration: -1
  #  encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/example?rewriteBatchedStatements=true&connectionTimeZone=SERVER
    username: example
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail: # ref: https://spring.pleiades.io/spring-boot/docs/current/reference/html/features.html#features.email
    protocol: smtp
    host: localhost
    port: 25
    username: *mail-address
    password: XXXXXXXX
    default-encoding: UTF-8
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: C:/work/tmp/springbootexample.log
  logback:
    rollingpolicy:
      file-name-pattern: C:/work/tmp/springbootexample.%d{yyyy-MM-dd}.log
      max-history: 30
  pattern:
    file:    "%date %-5level [%thread] [%X{REMOTE_ADDR:-undefined} - %X{USER_ID:-undefined}] %logger{2} [%file:%line %method] %msg%n"
    console: "%date %-5level [%thread] [%X{REMOTE_ADDR:-undefined} - %X{USER_ID:-undefined}] %logger{2} [%file:%line %method] %msg%n"
  group:
    transaction: "org.springframework.jdbc,org.springframework.transaction"
  level:
    root: WARN
    #transaction: DEBUG
    "[org.apache]": WARN
    "[org.jboss]": WARN
    "[org.springframework.boot]": INFO
    "[org.springframework]": WARN
    "[_org.springframework]": WARN
    "[org.thymeleaf]": WARN
    "[org.hibernate]": WARN
    "[org.mybatis]": WARN
    "[com.zaxxer]": WARN
    "[com.example.springboot]": INFO

application:
  aop-method-logging: false
  data-directory: *data-directory
  mail-address: *mail-address
  content:
    page-size: 100
  logging:
    mail:
      to-address: *mail-address
      subject: Spring Boot Example - logging mail
