package com.example.spring.config.security;

import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import lombok.Data;

/**
 * Custom UserDetails.
 */
@Data
@SuppressFBWarnings(
		value = { "EI_EXPOSE_REP", "EI_EXPOSE_REP2" },
		justification = "Allow to set collection values of form by Spring.")
public class UserDetailsImpl implements UserDetails {

	private String username;

	private String displayname;

	private String password;

	private boolean enabled;

	private Collection<GrantedAuthority> authorities;

	@SuppressFBWarnings(
			value = "SS_SHOULD_BE_STATIC",
			justification = "static is not required as getters are generated by lombok.")
	private final boolean accountNonExpired = true;

	@SuppressFBWarnings(
			value = "SS_SHOULD_BE_STATIC",
			justification = "static is not required as getters are generated by lombok.")
	private final boolean accountNonLocked = true;

	@SuppressFBWarnings(
			value = "SS_SHOULD_BE_STATIC",
			justification = "static is not required as getters are generated by lombok.")
	private final boolean credentialsNonExpired = true;

	private Integer sessiontimeout;

}
